from answer_engine_backend.pipeline.models import AnswerPolicy, AnswerResult, ContextPack


class AnswerGenerationStage:
    def execute(
        self,
        query: str,
        context_pack: ContextPack,
        answer_policy: AnswerPolicy,
    ) -> AnswerResult:
        answer_text = (
            "This is a stub Answer Engine response generated by the pipeline skeleton. "
            f"It received the query: '{query}' and used {len(context_pack.selected_chunks)} "
            "retrieved context chunk(s)."
        )
        return AnswerResult(
            answer_text=answer_text,
            token_usage={
                "prompt_tokens": max(1, context_pack.token_estimate),
                "completion_tokens": max(1, len(answer_text.split())),
                "total_tokens": context_pack.token_estimate + len(answer_text.split()),
            },
            model_metadata={
                "execution_mode": "stub",
                "response_style": answer_policy.response_style,
            },
        )
